name: Application Crash
description: Report a app crash
title: "Compile Error: <Title>"
labels: [Bug, App Crash]
body:
- type: markdown
  attributes:
    value: |
      If this is your first time opening an issue here, please read the [contributing guidelines](https://github.com/BEEmod/.github/blob/c865feea6f7f4bd9a65e8aaecac9c7731db9628f/contributing.md).
      
      Remember:
      - Do not open an issue if you are not using the latest BEEmod application and packages.
      - Make sure you're in the right place. Item and style related issues should go in the [BEE2-items repo](https://github.com/BEEmod/BEE2-items/).
      - Perform a search to make sure this issue hasn't already been reported.
      - Do not use the issue tracker to ask questions.
      - Issues should not be combined, unless they are very closely related (e.g. two bugs with a specific item in a specific case).
      - Make absolutely sure the issue is not UCP (User Created Packages) related
- type: input
  attributes:
    label: BEE2 Application Version
    description: Specify the version of BEE2.4 application (ex. 4.40.0 64bit)
  validations:
    required: true
- type: input
  attributes:
    label: BEE2 Package Version
    description: Specify the version of BEE2.4 packages (ex. 4.40.0)
  validations:
    required: true
- type: dropdown
  id: OS
  attributes:
    label: What operating system are you running on?
    multiple: true
    options:
      - Windows 10 (64bit)
      - Windows 10 (32bit)
      - Windows 8 (64bit)
      - Windows 8 (32bit)
      - Windows 7 (64bit)
      - Windows 7 (32bit)
      - Mac
      - Linux
      - Other
- type: textarea
  id: logs
  attributes:
    label: Logs and Reports
    description: Please copy and paste any relevant log output.
    render: shell
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional information
    description: Any more information you may have about the problem.
  validations:
    required: false
