name: Application Crash
description: Report a app crash
labels: [Bug, App Crash]
body:
  - type: markdown
    attributes:
      value: |
        If this is your first time opening an issue here, please read the [contributing guidelines](https://github.com/BEEmod/.github/blob/master/contributing.md).

        Remember:
        - Do not open an issue if you are not using the latest BEEmod application and packages.
        - Make sure you're in the right place. Item and style related issues should go in the [BEE2-items repo](https://github.com/BEEmod/BEE2-items/).
        - Perform a search to make sure this issue hasn't already been reported.
        - Please keep questions and general conversations to the Discussions tab or the Discord server, not the issue tracker.
        - Issues should not be combined, unless they are very closely related (e.g. two bugs with a specific item in a specific case).
        - Make absolutely sure the issue is not caused by a user-created package
  - type: input
    attributes:
      label: BEE2 Application Version
      description: Specify the version of BEE2.4 application (ex. 4.40.0 64bit). Don't use "latest", that isn't useful when looking back on issues in the future.
    validations:
      required: true
  - type: input
    attributes:
      label: BEE2 Package Version
      description: Specify the version of BEE2.4 packages (ex. 4.40.0).  Don't use "latest", that isn't useful when looking back on issues in the future.
    validations:
      required: true
  - type: input
    id: OS
    attributes:
      label: What operating system are you running on?
      description: If you are using Windows, please specify the version. If you are using Linux, please specify the distro and version.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and Reports
      description: Please copy and paste any relevant log output.
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Any more information you may have about the problem.
    validations:
      required: false
